# Changes here will be overwritten by Copier
_commit: acb4a69
_src_path: ../../templates/base
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: airflow-laminar
project_description: Common operators and tasks for airflow
project_name: airflow-common-operators
python_version_primary: '3.11'
team: the airflow-common-operators authors
