# Changes here will be overwritten by Copier
_commit: 8e4633d
_src_path: ../../templates/base
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Common operators and tasks for airflow
project_name: airflow-common-operators
python_version_primary: '3.11'
team: the airflow-common-operators authors
